# This is a basic workflow to help you get started with Actions

name: glpi

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      # Runs a single command using the runners shell
      - name: docker build
        run: |
          docker build . -t $DOCKER_USER/glpi:dev-$GITHUB_RUN_NUMBER
      - name: docker push
        run: |
          docker push $DOCKER_USER/glpi:dev-$GITHUB_RUN_NUMBER
      # Deploy to rke.dev cluster.
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: |
            set image deployment/glpi glpi=$"DOCKER_USER"/glpi:dev-$GITHUB_RUN_NUMBER --namespace rahglpi
